import { useState, useEffect, useMemo } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { Terminal, Copy, RefreshCw, Check, Search, Package } from 'lucide-react';
import { writeText } from '@tauri-apps/plugin-clipboard-manager';
import { useAppStore } from '@/store/useAppStore';
import { getText } from '@/lib/i18n';
import { EnvInfo } from '@/types/monitor';
import { cn } from '@/lib/utils';

export function EnvFingerprint() {
  const { language } = useAppStore();
  const [data, setData] = useState<EnvInfo[]>([]);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [filter, setFilter] = useState('');

  const fetchData = async () => {
    setLoading(true);
    try {
      const res = await invoke<EnvInfo[]>('get_env_info');
      setData(res);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  // 挂载时加载一次
  useEffect(() => {
    fetchData();
  }, []);

  const filteredData = useMemo(() => {
    const q = filter.toLowerCase();
    return data.filter(item => 
      item.name.toLowerCase().includes(q) || 
      item.version.toLowerCase().includes(q)
    );
  }, [data, filter]);

  const handleCopyReport = async () => {
    const installed = data.filter(i => i.version !== 'Not Found');
    const missing = data.filter(i => i.version === 'Not Found');
    
    let report = `### Dev Environment Report\nGenerated by CodeForge AI on ${new Date().toLocaleString()}\n\n`;
    
    report += `#### Installed Tools (${installed.length})\n`;
    report += `| Tool | Version |\n|------|---------|\n`;
    report += installed.map(i => `| **${i.name}** | \`${i.version}\` |`).join('\n');
    
    if (missing.length > 0) {
        report += `\n\n#### Missing / Not Found (${missing.length})\n`;
        report += missing.map(i => `- ${i.name}`).join('\n');
    }

    await writeText(report);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="h-full flex flex-col p-6 animate-in fade-in duration-300">
      
      {/* Toolbar */}
      <div className="flex flex-col gap-4 mb-6 shrink-0">
          <div className="flex justify-between items-center">
             <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <Package size={16} />
                <span>Detected <strong className="text-foreground">{data.filter(i => i.version !== 'Not Found').length}</strong> tools</span>
             </div>
             <div className="flex gap-2">
                <button 
                    onClick={handleCopyReport}
                    className="flex items-center gap-2 px-3 py-1.5 bg-secondary hover:bg-secondary/80 rounded-lg text-xs font-medium transition-colors border border-transparent hover:border-border"
                >
                    {copied ? <Check size={14} className="text-green-500" /> : <Copy size={14} />}
                    {getText('monitor', 'copyReport', language)}
                </button>
                <button 
                    onClick={fetchData}
                    disabled={loading}
                    className="p-1.5 hover:bg-secondary rounded-lg transition-colors disabled:opacity-50 border border-transparent hover:border-border"
                >
                    <RefreshCw size={16} className={cn(loading && "animate-spin")} />
                </button>
             </div>
          </div>

          {/* Search Input */}
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={14} />
            <input 
                className="w-full bg-secondary/30 border border-border rounded-lg pl-9 pr-4 py-2 text-xs focus:outline-none focus:ring-2 focus:ring-primary/20 transition-all placeholder:text-muted-foreground/50"
                placeholder="Filter tools..."
                value={filter}
                onChange={e => setFilter(e.target.value)}
            />
          </div>
      </div>

      {/* Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 overflow-y-auto custom-scrollbar p-1">
         {filteredData.map((item) => {
            const isInstalled = item.version !== 'Not Found';
            return (
                <div key={item.name} className={cn(
                    "border p-3 rounded-xl flex items-center gap-3 transition-all duration-200 group",
                    isInstalled 
                        ? "bg-card border-border hover:border-primary/30 hover:shadow-sm" 
                        : "bg-secondary/20 border-transparent opacity-60 hover:opacity-100"
                )}>
                    <div className={cn(
                        "w-10 h-10 rounded-lg flex items-center justify-center shrink-0 transition-colors", 
                        isInstalled ? "bg-primary/10 text-primary" : "bg-secondary text-muted-foreground"
                    )}>
                        <Terminal size={18} />
                    </div>
                    <div className="min-w-0 flex-1">
                        <div className="flex items-center justify-between">
                            <div className="text-xs font-bold text-foreground/80 uppercase tracking-wider">{item.name}</div>
                            {isInstalled && <Check size={12} className="text-green-500 opacity-0 group-hover:opacity-100 transition-opacity" />}
                        </div>
                        <div className={cn(
                            "text-sm truncate mt-0.5 font-mono", 
                            isInstalled ? "text-muted-foreground" : "text-muted-foreground/40 italic"
                        )} title={item.version}>
                            {item.version}
                        </div>
                    </div>
                </div>
            )
         })}
         
         {/* Empty State */}
         {!loading && filteredData.length === 0 && (
             <div className="col-span-full py-10 flex flex-col items-center justify-center text-muted-foreground opacity-50">
                 <Search size={32} className="mb-2" />
                 <p className="text-sm">No tools found matching "{filter}"</p>
             </div>
         )}

         {/* 骨架屏 (Loading state) */}
         {loading && data.length === 0 && Array.from({length: 9}).map((_, i) => (
             <div key={i} className="bg-card border border-border p-3 rounded-xl flex gap-3 animate-pulse">
                 <div className="w-10 h-10 bg-secondary rounded-lg" />
                 <div className="flex-1 space-y-2 py-1.5">
                     <div className="h-3 bg-secondary rounded w-1/3" />
                     <div className="h-3 bg-secondary rounded w-2/3" />
                 </div>
             </div>
         ))}
      </div>
    </div>
  );
}