import { useState, useMemo } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { 
  Terminal, Copy, RefreshCw, Check, Search, 
  Cpu, Globe, Code2, Layers, Database, Box, 
  AppWindow, Wrench, Play
} from 'lucide-react';
import { writeText } from '@tauri-apps/plugin-clipboard-manager';
import { useAppStore } from '@/store/useAppStore';
import { useContextStore } from '@/store/useContextStore'; // 获取项目路径
import { getText } from '@/lib/i18n';
import { EnvReport, ToolInfo } from '@/types/monitor';
import { cn } from '@/lib/utils';

export function EnvFingerprint() {
  const { language } = useAppStore();
  const { projectRoot } = useContextStore(); // 获取当前项目根目录用于扫描 npm 包
  
  const [data, setData] = useState<EnvReport | null>(null);
  const [loading, setLoading] = useState(false);
  const [hasScanned, setHasScanned] = useState(false); // 标记是否点击过检测
  const [copied, setCopied] = useState(false);
  const [filter, setFilter] = useState('');

  const fetchData = async () => {
    setLoading(true);
    setHasScanned(true); // 标记已开始
    try {
      // 传入 projectPath 以便后端扫描 package.json
      const res = await invoke<EnvReport>('get_env_info', { projectPath: projectRoot });
      setData(res);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  // --- 深度过滤逻辑 ---
  const filteredData = useMemo(() => {
    if (!data) return null;
    const q = filter.toLowerCase().trim();
    if (!q) return data;

    // 辅助函数：过滤 ToolInfo 数组
    const filterTools = (list: ToolInfo[]) => 
      list.filter(t => t.name.toLowerCase().includes(q) || t.version.toLowerCase().includes(q));

    // 辅助函数：过滤 SDK Map
    const filterSdks = (sdks: Record<string, string[]>) => {
      const res: Record<string, string[]> = {};
      Object.entries(sdks).forEach(([key, vals]) => {
        if (key.toLowerCase().includes(q) || vals.some(v => v.toLowerCase().includes(q))) {
          res[key] = vals;
        }
      });
      return res;
    };

    return {
      system: data.system, // System 信息不过滤，保留显示上下文
      binaries: filterTools(data.binaries),
      browsers: filterTools(data.browsers),
      ides: filterTools(data.ides),
      languages: filterTools(data.languages),
      virtualization: filterTools(data.virtualization),
      utilities: filterTools(data.utilities),
      managers: filterTools(data.managers),
      databases: filterTools(data.databases),
      npm_packages: filterTools(data.npm_packages),
      sdks: filterSdks(data.sdks),
    };
  }, [data, filter]);

  // --- 生成 Markdown 报告 ---
  const handleCopyReport = async () => {
    if (!data) return;
    
    let report = `## Environment Report\nGenerated by CodeForge AI on ${new Date().toLocaleString()}\n\n`;
    
    // System
    if (data.system) {
      report += `### System\n`;
      Object.entries(data.system).forEach(([k, v]) => report += `- **${k}**: ${v}\n`);
      report += `\n`;
    }

    // Helper to print lists
    const printSection = (title: string, list: ToolInfo[]) => {
      const valid = list.filter(i => i.version !== 'Not Found' && i.version !== 'Not Installed');
      if (valid.length === 0) return;
      report += `### ${title}\n`;
      valid.forEach(i => {
        report += `- ${i.name}: \`${i.version}\`${i.path ? ` - *${i.path}*` : ''}\n`;
      });
      report += `\n`;
    };

    printSection('Binaries', data.binaries);
    printSection('Languages', data.languages);
    printSection('Browsers', data.browsers);
    printSection('IDEs', data.ides);
    printSection('Databases', data.databases);
    printSection('Virtualization', data.virtualization);
    printSection('Utilities', data.utilities);
    printSection('Managers', data.managers);
    printSection('NPM Packages', data.npm_packages);

    // SDKs
    if (Object.keys(data.sdks).length > 0) {
        report += `### SDKs\n`;
        Object.entries(data.sdks).forEach(([key, vals]) => {
            report += `- **${key}**:\n`;
            vals.forEach(v => report += `  - ${v}\n`);
        });
    }

    await writeText(report);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // --- 初始未检测状态 ---
  if (!hasScanned) {
    return (
      <div className="h-full flex flex-col items-center justify-center p-6 animate-in fade-in zoom-in-95 duration-300">
        <div className="w-20 h-20 bg-primary/10 rounded-full flex items-center justify-center mb-6 text-primary shadow-[0_0_30px_rgba(59,130,246,0.2)]">
           <Wrench size={40} />
        </div>
        <h2 className="text-xl font-bold mb-2 text-foreground">{getText('monitor', 'navEnv', language)}</h2>
        <p className="text-muted-foreground text-center max-w-md mb-8 text-sm leading-relaxed">
           Deep scan your development environment to detect installed tools, versions, IDEs, databases, and project dependencies.
        </p>
        <button 
          onClick={fetchData}
          className="group relative flex items-center gap-3 px-8 py-3 bg-primary text-primary-foreground rounded-full font-semibold shadow-lg hover:shadow-primary/25 hover:scale-105 transition-all active:scale-95"
        >
           {loading ? <RefreshCw size={20} className="animate-spin" /> : <Play size={20} className="fill-current" />}
           <span>Start Environment Scan</span>
        </button>
      </div>
    );
  }

  // --- 渲染辅助组件 ---
  const Section = ({ title, icon: Icon, items }: { title: string, icon: any, items: ToolInfo[] }) => {
    if (!items || items.length === 0) return null;
    return (
      <div className="mb-6 break-inside-avoid">
        <h3 className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-3 flex items-center gap-2 border-b border-border/50 pb-1">
          <Icon size={14} /> {title}
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3">
          {items.map((item, idx) => {
             const isFound = item.version !== 'Not Found' && item.version !== 'Not Installed';
             return (
              <div key={`${item.name}-${idx}`} className={cn(
                "border rounded-lg p-3 flex flex-col gap-1 transition-all",
                isFound 
                  ? "bg-card border-border hover:border-primary/30" 
                  : "bg-secondary/10 border-transparent opacity-60"
              )}>
                <div className="flex justify-between items-start">
                   <span className="font-semibold text-sm">{item.name}</span>
                   {isFound && <Check size={12} className="text-green-500 mt-1" />}
                </div>
                <div className={cn("text-xs font-mono truncate", isFound ? "text-muted-foreground" : "text-muted-foreground/40 italic")}>
                   {item.version}
                </div>
                {item.path && <div className="text-[10px] text-muted-foreground/40 truncate mt-1" title={item.path}>{item.path}</div>}
              </div>
             )
          })}
        </div>
      </div>
    );
  };

  return (
    <div className="h-full flex flex-col p-6 animate-in fade-in duration-300">
      
      {/* Toolbar */}
      <div className="flex flex-col gap-4 mb-4 shrink-0">
          <div className="flex justify-between items-center">
             <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <Globe size={16} />
                <span>Environment Fingerprint</span>
             </div>
             <div className="flex gap-2">
                <button 
                    onClick={handleCopyReport}
                    className="flex items-center gap-2 px-3 py-1.5 bg-secondary hover:bg-secondary/80 rounded-lg text-xs font-medium transition-colors border border-transparent hover:border-border"
                >
                    {copied ? <Check size={14} className="text-green-500" /> : <Copy size={14} />}
                    {getText('monitor', 'copyReport', language)}
                </button>
                <button 
                    onClick={fetchData}
                    disabled={loading}
                    className="p-1.5 hover:bg-secondary rounded-lg transition-colors disabled:opacity-50 border border-transparent hover:border-border"
                    title="Rescan"
                >
                    <RefreshCw size={16} className={cn(loading && "animate-spin")} />
                </button>
             </div>
          </div>

          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={14} />
            <input 
                className="w-full bg-secondary/30 border border-border rounded-lg pl-9 pr-4 py-2 text-xs focus:outline-none focus:ring-2 focus:ring-primary/20 transition-all placeholder:text-muted-foreground/50"
                placeholder={getText('monitor', 'envToolFilter', language)}
                value={filter}
                onChange={e => setFilter(e.target.value)}
            />
          </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 overflow-y-auto custom-scrollbar p-1 pb-10">
         {loading && !filteredData && (
             <div className="flex flex-col items-center justify-center py-20 text-muted-foreground gap-3">
                 <RefreshCw size={24} className="animate-spin text-primary" />
                 <span className="text-sm">Scanning system environment...</span>
             </div>
         )}

         {filteredData && (
            <div className="space-y-6">
                {/* 1. System Info (Top Card) */}
                {filteredData.system && (
                    <div className="bg-gradient-to-br from-secondary/50 to-background border border-border p-4 rounded-xl shadow-sm mb-6">
                        <h3 className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-3 flex items-center gap-2"><Cpu size={14}/> System</h3>
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                            {Object.entries(filteredData.system).map(([k, v]) => (
                                <div key={k} className="flex flex-col">
                                    <span className="text-[10px] text-muted-foreground uppercase">{k}</span>
                                    <span className="font-mono text-sm font-medium">{v}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {/* 2. Tool Sections */}
                <Section title="Binaries" icon={Terminal} items={filteredData.binaries} />
                <Section title="Languages" icon={Code2} items={filteredData.languages} />
                <Section title="Browsers" icon={Globe} items={filteredData.browsers} />
                <Section title="IDEs" icon={AppWindow} items={filteredData.ides} />
                <Section title="Databases" icon={Database} items={filteredData.databases} />
                <Section title="Virtualization" icon={Layers} items={filteredData.virtualization} />
                <Section title="NPM Packages (Current Project)" icon={Box} items={filteredData.npm_packages} />
                <Section title="Managers" icon={Wrench} items={filteredData.managers} />
                <Section title="Utilities" icon={Terminal} items={filteredData.utilities} />

                {/* 3. SDKs (Special Render) */}
                {Object.keys(filteredData.sdks).length > 0 && (
                    <div className="mb-6">
                        <h3 className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-3 flex items-center gap-2 border-b border-border/50 pb-1">
                            <Layers size={14} /> SDKs
                        </h3>
                        <div className="grid grid-cols-1 gap-3">
                            {Object.entries(filteredData.sdks).map(([name, versions]) => (
                                <div key={name} className="border border-border bg-card rounded-lg p-3">
                                    <span className="font-semibold text-sm block mb-1">{name}</span>
                                    <div className="flex flex-wrap gap-2">
                                        {versions.map((v, i) => (
                                            <span key={i} className="text-xs font-mono bg-secondary px-1.5 py-0.5 rounded text-muted-foreground">
                                                {v}
                                            </span>
                                        ))}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                )}
                
                {/* Empty State for Filter */}
                {Object.keys(filteredData.system || {}).length === 0 && filteredData.binaries.length === 0 && (
                    <div className="text-center py-10 text-muted-foreground opacity-50">
                        No matches found.
                    </div>
                )}
            </div>
         )}
      </div>
    </div>
  );
}